    - name: wordpress download
      get_url: url=https://ja.wordpress.org/wordpress-4.2.2-ja.zip dest=/tmp use_proxy=yes
          #shell: wget "https://ja.wordpress.org/wordpress-4.2.2-ja.zip"
    - name: unzip insall
      yum: name=unzip state=installed

    - name: unzip wordpress
      shell: unzip wordpress-4.2.2-ja.zip chdir=/tmp

    - name: wordpress move
      shell: mv /tmp/wordpress /usr/share/nginx/html

    - name: wp-config.php
      template:
           src: ../wp-config.php.j2
           dest: /usr/share/nginx/html/wordpress/wp-config.php


